on:
  push:
    branches:
      - main
  workflow_dispatch:
name: Deploy website
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout latest code"
        uses: actions/checkout@v3